--SAAS化改造添加及修改的表（20100317）

CREATE TABLE SAAS_TENANT (id VARCHAR2(255) NOT NULL, tenantId VARCHAR2(255) UNIQUE NULL, DTYPE VARCHAR2(255),  NAME VARCHAR2(255)  NULL, VERSION NUMBER(10) NULL,  CREATETIME TIMESTAMP NULL, LASTMODIFYTIME TIMESTAMP NULL, LASTMODIFIER VARCHAR2(255) NULL, CREATOR VARCHAR2(255) NULL, DESCRIPTION VARCHAR2(255) NULL, LIFECYCLESTATUS NUMBER(5) NULL, STATUS NUMBER(5) NULL, PRIMARY KEY (id))
--umprinciple
ALTER TABLE UM_Principle ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_Principle ADD CONSTRAINT UM_Principle_SAAS_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--iprange
ALTER TABLE UM_IPRange ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_IPRange ADD CONSTRAINT UM_IPRange_SAAS_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--IPSegment
ALTER TABLE UM_IPSegment ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_IPSegment ADD CONSTRAINT UM_IPSegment_SAAS_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--GeneralResource
ALTER TABLE UM_GeneralResource ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_GeneralResource ADD CONSTRAINT UM_GResource_SAAS_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--PermissionRule
ALTER TABLE UM_PermissionRule ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_PermissionRule ADD CONSTRAINT UM_PRule_SAAS_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--Role
ALTER TABLE UM_Role ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_Role ADD CONSTRAINT UM_Role_SAAS_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--UserRule
ALTER TABLE UM_UserRule ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_UserRule ADD CONSTRAINT UM_UserRule_SAAS_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--LogItem
ALTER TABLE UM_LogItem ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_LogItem ADD CONSTRAINT UM_LogItem_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--MultiSynTaskConfigInfo
ALTER TABLE UM_SYN_TASK ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_SYN_TASK ADD CONSTRAINT UM_SYN_TASK_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--MultiSynTaskLogInfo
ALTER TABLE UM_SYN_TASK_LOG ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_SYN_TASK_LOG ADD CONSTRAINT UM_SYN_TASK_LOG_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--AdditionalId
ALTER TABLE UM_AdditionalId ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_AdditionalId ADD CONSTRAINT UM_AdditionalId_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--AuthCenter
ALTER TABLE UM_AuthCenter ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_AuthCenter ADD CONSTRAINT UM_AuthCenter_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--Card
ALTER TABLE UM_Card ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_Card ADD CONSTRAINT UM_Card_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--Cash
ALTER TABLE UM_Cash ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_Cash ADD CONSTRAINT UM_Cash_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--Contactor
ALTER TABLE UM_Contactor ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_Contactor ADD CONSTRAINT UM_Contactor_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--HistoryCard
ALTER TABLE UM_HistoryCard ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_HistoryCard ADD CONSTRAINT UM_HistoryCard_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)
--Organization
ALTER TABLE UM_Organization ADD TENANT_ID VARCHAR2(255) NULL
ALTER TABLE UM_Organization ADD CONSTRAINT UM_Organization_TENANT_id FOREIGN KEY (TENANT_ID) REFERENCES SAAS_TENANT (id)


ALTER table UM_Principle add userGroup NUMBER(10)
ALTER table UM_Principle add maxConcurrentNumber NUMBER(10)
ALTER table UM_Principle add background NUMBER(10)
ALTER table UM_Principle add directlyUser NUMBER(1) default 0
ALTER table UM_Principle add collegeName VARCHAR2(255)
ALTER table UM_Principle add departmentName VARCHAR2(255)
ALTER table UM_Principle add professionalName VARCHAR2(255)
ALTER table UM_Principle add localRegisted NUMBER(1) default 1