--成员馆管理员权限
insert into um_role (ID, DTYPE, ENABLED, TYPE, VERSION, NAME, CREATETIME, LASTMODIFYTIME, LASTMODIFIER, CREATOR, DESCRIPTION, LIFECYCLESTATUS, UMROLEOWNER_ID, UMROLEPARENT_ID, APPLICATION_ID) values ('$memberadmin_role', 'Role', 1, 1, 28, '成员馆管理员角色', to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), 'administrator', 'administrator', '', 4, '$administrator', '$admin_role', '')

insert into um_userrule (ID, OPERATIONS, ENABLED, EXPRESSION, VERSION, NAME, TYPE, AUTHABLE, ENTITYLIMITTYPE, CREATETIME, LASTMODIFYTIME, LASTMODIFIER, CREATOR, DESCRIPTION, LIFECYCLESTATUS) values ('$memberadmin_rule_u', '', 1, 'u.userType=9000&u.status=2', 3, '成员馆管理员规则', 0, 0, 'com.cnebula.um.ejb.entity.usr.UMPrincipal', to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), 'administrator', 'administrator', '', 4)

insert into um_role_userrule (ROLE_ID, RULE_ID) values ('$memberadmin_role', '$memberadmin_rule_u')

insert into um_permissionrule (ID, OPERATIONS, ENABLED, EXPRESSION, VERSION, NAME, TYPE, AUTHABLE, ENTITYLIMITTYPE, CREATETIME, LASTMODIFYTIME, LASTMODIFIER, CREATOR, DESCRIPTION, LIFECYCLESTATUS) values ('$memberadmin_user', 'activate,changePassword,update,stop,verify,delete,create,view', 1, 'organization.id=cu.organization.id', 7, '成员馆用户管理规则', 0, 1, 'com.cnebula.um.ejb.entity.usr.UMPrincipal', to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), 'administrator', 'administrator', '', 4)
insert into um_permissionrule (ID, OPERATIONS, ENABLED, EXPRESSION, VERSION, NAME, TYPE, AUTHABLE, ENTITYLIMITTYPE, CREATETIME, LASTMODIFYTIME, LASTMODIFIER, CREATOR, DESCRIPTION, LIFECYCLESTATUS) values ('$memberadmin_role', 'update,view,view.id,view.uMUserRules,view.uMPermissionRules,view.name,view.enabled,view.uMRoleOwner,view.type,view.uMRoleParent,update.uMUserRules,update.uMPermissionRules,update.enabled', 1, '', 11, '成员馆角色管理', 0, 1, 'com.cnebula.um.ejb.entity.perm.Role',to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), 'administrator', 'administrator', '', 4)
insert into um_permissionrule (ID, OPERATIONS, ENABLED, EXPRESSION, VERSION, NAME, TYPE, AUTHABLE, ENTITYLIMITTYPE, CREATETIME, LASTMODIFYTIME, LASTMODIFIER, CREATOR, DESCRIPTION, LIFECYCLESTATUS) values ('$all_permission_true_rule', '', 1, 'true', 2, '全部允许权限规则', 0, 0, '', to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), to_timestamp('25-11-2009 15:33:21.070000', 'dd-mm-yyyy hh24:mi:ss.ff'), 'administrator', 'administrator', '', 4);

insert into um_role_permissionrule (ROLE_ID, RULE_ID) values ('$memberadmin_role', '$memberadmin_user')
insert into um_role_permissionrule (ROLE_ID, RULE_ID) values ('$memberadmin_role', '$memberadmin_role')